### ISSUE TITLE
Easier to search for cycles in autocompletion

### ISSUE THREAD

**Issue by rosariotaormina-isg** [isg-stuttgart/vscode-isg-cnc#150]
You could perhaps first select the categories, such as drill, mill, measures... and then the associated cycles. If all cycles are listed at once, you may have to scroll for quite a long time

**Comment by JurekSeverin** [comment]
Doing this with subcategories is not possible (at least with my current state of knowledge).
The snippets are filtered with string-comparison. Instead of writing the complete prefix like "L Cycle[Name=...." you can just write a characteristic infix like "drill" and you should see the fitting suggestions for Cycle snippets containing "drill".
